Repository Longhorn-Developers/UT-Registration-Plus, pull requests merged in 2024-02, with the labels that each got.

#60 feat: Calendar Components 3rd Attempt at Merging
  package-lock.json
  src/stories/components/CalendarGrid.stories.tsx
  src/views/components/common/CalendarGrid/CalendarGrid.module.scss
  src/views/components/common/CalendarGrid/CalendarGrid.tsx
  src/views/components/common/CalendarGridCell/CalendarGridCell.module.scss
  src/views/components/common/CalendarGridCell/CalendarGridCell.tsx
Labels: awaiting-changes

#70 feat: updated Text component to latest design specification
  public/fonts/roboto-flex.woff2
  src/stories/components/Text.stories.tsx
  src/views/components/common/Text/Text.module.scss
  src/views/components/common/Text/Text.tsx
  src/views/styles/fonts.module.scss
  src/views/styles/fonts.module.scss.d.ts
Labels: ready-for-review

#103 feat: Conventional Commits
  .husky/commit-msg
  commitlint.config.ts
  package.json
  pnpm-lock.yaml
Labels: ready-for-review, utrp-v2

#102 feat: Best Practices
  .eslintrc
  .github/workflows/best-practices.yml
  .github/workflows/tests.yml
  package.json
  pnpm-lock.yaml
  src/shared/util/colors.ts
  src/shared/util/tests/colors.test.ts
  src/shared/util/tests/random.test.ts
  src/shared/util/tests/string.test.ts
  src/shared/util/tests/time.test.ts
  src/views/hooks/tests/useFlattenedCourseSchedule.test.ts
  src/views/hooks/useFlattenedCourseSchedule.ts
  vitest.config.ts
Labels: utrp-v2
