Repository Longhorn-Developers/UT-Registration-Plus, pull requests merged in 2024-10, with the labels that each got.

#229 feat: switch button
  src/stories/components/ToggleSwitch.stories.tsx
  src/views/components/common/SwitchButton.tsx
Labels: ready-for-review, awaiting-changes, feature, UI/UX-figma

#241 docs: update readme for UTRP v2 prod release
  README.md
Labels: utrp-v2, docs

#255 style: getting our minecraft splash text the way we need
  src/views/components/PopupMain.tsx
Labels: ready-for-review, UI/UX-figma

#254 chore: update packages
  package.json
  patches/@unocss__vite.patch
  patches/@unocss__vite@0.58.6.patch
  pnpm-lock.yaml
Labels: ready-for-review, dependencies

#272 feat: limit schedules to 10
  src/views/components/calendar/CalendarSchedules.tsx
Labels: ready-for-review, feature

#280 build: add pnpm run build:watch
  package.json
Labels: ready-for-review, utrp-v2

#281 feat: readme animation
  README.md
Labels: ready-for-review, docs

#273 feat: async course adding and async/other course block adjustments
  src/views/components/calendar/CalendarBottomBar.tsx
  src/views/components/calendar/CalendarCourseCell.tsx
  src/views/hooks/useFlattenedCourseSchedule.ts
Labels: ready-for-review, feature

#275 chore: add js-doc
  src/pages/background/util/openNewTab.ts
  src/shared/types/MIMEType.ts
  src/shared/types/ThemeColors.ts
  src/shared/util/colors.ts
  src/views/components/common/Chip.tsx
  src/views/components/common/Dialog.tsx
  src/views/components/common/DialogProvider/DialogProvider.tsx
Labels: ready-for-review, docs

#284 fix: disabled [object Object] hover message on dialog popups
  src/views/components/common/Dialog.tsx
Labels: ready-for-review, bugfix

#286 fix: duplicate schedule name regex no longer grabs trailing white space
  src/pages/background/lib/handleDuplicate.ts
Labels: bugfix

#260 feat: settings page
  package.json
  pnpm-lock.yaml
  src/assets/LD-icon.png
  src/debug/index.tsx
  src/pages/background/lib/deleteSchedule.ts
  src/pages/calendar/CalendarMain.tsx
  src/pages/options/Settings.tsx
  src/pages/options/index.tsx
  src/shared/storage/OptionsStore.ts
  src/shared/util/experimental.ts
  src/stories/components/Settings.stories.tsx
  src/views/components/PopupMain.tsx
  src/views/components/Settings.tsx
  src/views/components/calendar/CalendarCourseCell.tsx
  src/views/components/calendar/CalenderHeader.tsx
  src/views/components/common/PopupCourseBlock.tsx
  src/views/components/common/SwitchButton.tsx
  src/views/components/injected/TableRow/TableRow.module.scss
  src/views/components/injected/TableRow/TableRow.tsx
  src/views/components/settings/DevMode.tsx
  src/views/components/settings/Preview.tsx
  src/views/components/settings/Settings.tsx
  src/views/lib/getGitHubStats.ts
Labels: ready-for-review, utrp-v2, feature, UI/UX-figma

#288 fix(ui): unhid settings button
  src/views/components/calendar/CalenderHeader.tsx
Labels: blocked, feature

#293 feat: migration update showing
  src/stories/components/UpdateText.stories.tsx
  src/views/components/common/UpdateText.tsx
Labels: utrp-v2, feature

#283 feat: release notes
  .nvmrc
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
  scripts/generateChangelog.ts
  scripts/release.ts
  src/stories/components/ChangelogPopup.stories.tsx
  src/views/components/common/ChangelogPopup.tsx
  src/views/hooks/useChangelog.tsx
  tsconfig.json
  utils/git/getSourceRef.ts
  utils/log.ts
Labels: ready-for-review, utrp-v2, feature, docs

#296 feat: splash text additions before v2 release
  src/assets/insideJokes.tsx
Labels: ready-for-review, utrp-v2, feature

#292 feat: UTRP v2 migration
  package.json
  pnpm-lock.yaml
  src/pages/background/background.ts
  src/pages/background/lib/createSchedule.ts
  src/pages/background/lib/migrateUTRPv1Courses.ts
  src/pages/calendar/CalendarMain.tsx
  src/pages/options/Settings.tsx
  src/pages/popup/index.tsx
  src/pages/report/index.tsx
  src/shared/util/checkLoginStatus.ts
  src/views/components/PopupMain.tsx
  src/views/components/ReportIssueMain.tsx
  src/views/components/calendar/Calendar.tsx
  src/views/components/common/Button.tsx
  src/views/components/common/DialogProvider/DialogProvider.tsx
  src/views/components/common/MigrationDialog.tsx
  src/views/components/settings/Settings.tsx
  src/views/contexts/DialogContext.ts
  src/views/contexts/SentryContext.tsx
  src/views/hooks/useCourseFromUrl.ts
  src/views/hooks/useSchedules.ts
  src/views/lib/CourseCatalogScraper.ts
  src/views/lib/courseMigration.ts
Labels: ready-for-review, utrp-v2, dependencies, feature, UI/UX-figma

#308 chore: get ready for release
  .gitignore
  CHANGELOG.md
  gulpfile.js
  package.json
  pnpm-lock.yaml
  src/pages/background/background.ts
  src/pages/options/index.html
  src/views/components/PopupMain.tsx
  src/views/components/ReportIssueMain.tsx
  src/views/components/calendar/CalenderHeader.tsx
  src/views/components/common/List.tsx
  src/views/components/common/MigrationDialog.tsx
  src/views/components/settings/Settings.tsx
  src/views/contexts/DialogContext.ts
  src/views/contexts/SentryContext.tsx
  src/views/hooks/useChangelog.tsx
  tsconfig.json
  utils/plugins/run-command-on-demand.ts
  vite.config.ts
Labels: utrp-v2, dependencies

#310 feat: swe title updates
  src/views/components/settings/Settings.tsx
  src/views/lib/getGitHubStats.ts
Labels: ready-for-review, utrp-v2, docs

#314 fix(build): gulp zip
  gulpfile.js
Labels: build

#367 feat: update useful links
  src/views/components/calendar/ImportantLinks.tsx
Labels: ready-for-review, UI/UX-figma

#377 chore: One red color of #D10000
  src/shared/types/ThemeColors.ts
  src/views/components/common/MigrationDialog.tsx
  src/views/components/common/ScheduleListItem.tsx
  src/views/components/settings/Settings.tsx
  src/views/styles/colors.module.scss
Labels: UI/UX-figma

#372 feat: add core curriculum chips to injected popup
  src/shared/types/Course.ts
  src/stories/components/Chip.stories.tsx
  src/stories/components/ConflictsWithWarning.stories.tsx
  src/stories/components/List.stories.tsx
  src/stories/components/PopupCourseBlock.stories.tsx
  src/stories/components/calendar/CalendarBottomBar.stories.tsx
  src/stories/injected/mocked.ts
  src/views/components/common/Chip.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
  src/views/lib/CourseCatalogScraper.ts
Labels: feature

#389 fix(build): sentry sourcemap issues
  @types/vite-env.d.ts
  package.json
  src/views/contexts/SentryContext.tsx
  vite.config.ts
Labels: ready-for-review, bugfix, build

#395 fix(ui): main popup now shows 0 for empty schedule
  src/pages/background/background.ts
  src/shared/util/updateBadgeText.ts
Labels: bugfix
