Repository Longhorn-Developers/UT-Registration-Plus, pull requests merged in 2024-05, with the labels that each got.

#198 feat: DialogProvider component
  src/stories/components/DialogProvider.stories.tsx
  src/tsconfig.json
  src/views/components/common/Dialog.tsx
  src/views/components/common/DialogProvider/DialogProvider.tsx
  src/views/contexts/DialogContext.ts
Labels: ready-for-review, feature

#211 feat: rerouted directory to syllabus when click on professor name
  src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
Labels: ready-for-review, UI/UX-figma

#224 feat: additional changes to #201
  src/stories/components/LogoIcon.stories.tsx
  src/views/components/calendar/CalenderHeader.tsx
  src/views/components/common/LogoIcon.tsx
Labels: ready-for-review, feature, UI/UX-figma
