Repository Longhorn-Developers/UT-Registration-Plus, pull requests merged in 2024-03, with the labels that each got.

#184 refactor: remove component subfolders
  src/pages/calendar/CalendarMain.tsx
  src/stories/components/Button.stories.tsx
  src/stories/components/Card.stories.tsx
  src/stories/components/Chip.stories.tsx
  src/stories/components/ConflictsWithWarning.stories.tsx
  src/stories/components/CourseStatus.stories.tsx
  src/stories/components/Divider.stories.tsx
  src/stories/components/Dropdown.stories.tsx
  src/stories/components/InfoCard.stories.tsx
  src/stories/components/Link.stories.ts
  src/stories/components/List.stories.tsx
  src/stories/components/PopupCourseBlock.stories.tsx
  src/stories/components/Prompt.stories.tsx
  src/stories/components/SchedulTotalHoursAndCourses.stories.tsx
  src/stories/components/ScheduleListItem.stories.tsx
  src/stories/components/calendar/Calendar.stories.tsx
  src/stories/components/calendar/CalendarBottomBar.stories.tsx
  src/stories/components/calendar/CalendarCourse.stories.tsx
  src/stories/components/calendar/CalendarCourseCell.stories.tsx
  src/stories/components/calendar/CalendarGrid.stories.tsx
  src/stories/components/calendar/CalendarGridCell.stories.tsx
  src/stories/components/calendar/CalendarHeader.stories.tsx
  src/stories/components/calendar/CalendarSchedules.stories.tsx
  src/views/components/PopupMain.tsx
  src/views/components/calendar/Calendar.tsx
  src/views/components/calendar/CalendarBottomBar.tsx
  src/views/components/calendar/CalendarCourseBlock/CalendarCourseMeeting.module.scss
  src/views/components/calendar/CalendarCourseBlock/CalendarCourseMeeting.tsx
  src/views/components/calendar/CalendarCourseCell.tsx
  src/views/components/calendar/CalendarCourseCellColorPicker/CourseCellColorPicker.tsx
  src/views/components/calendar/CalendarFooter.tsx
  src/views/components/calendar/CalendarGrid.tsx
  src/views/components/calendar/CalendarGridCell.tsx
  src/views/components/calendar/CalendarSchedules.tsx
  src/views/components/calendar/CalenderHeader.tsx
  src/views/components/common/Button.tsx
  src/views/components/common/Card/Card.module.scss
  src/views/components/common/Card/Card.tsx
  src/views/components/common/Chip.tsx
  src/views/components/common/ConflictsWithWarning.tsx
  src/views/components/common/CourseStatus.tsx
  src/views/components/common/Dialog.tsx
  src/views/components/common/Divider.tsx
  src/views/components/common/InfoCard.tsx
  src/views/components/common/Link.tsx
  src/views/components/common/List.tsx
  src/views/components/common/PopupCourseBlock.tsx
  src/views/components/common/Prompt.tsx
  src/views/components/common/ScheduleDropdown.tsx
  src/views/components/common/ScheduleListItem.tsx
  src/views/components/common/ScheduleTotalHoursAndCourses.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/CourseCatalogInjectedPopup.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
  src/views/components/injected/RecruitmentBanner/RecruitmentBanner.tsx
  src/views/components/injected/TableRow/TableRow.tsx
  src/views/hooks/useFlattenedCourseSchedule.ts
Labels: ready-for-review

#186 feat: use downloadBlob util
  src/shared/types/MIMEType.ts
  src/shared/util/downloadBlob.ts
  src/views/components/calendar/utils.ts
Labels: ready-for-review, utrp-v2, feature

#180 feat: screenshot whole page, hide certain elements, screenshot fixed size
  src/shared/util/downloadBlob.ts
  src/stories/components/calendar/CalendarBottomBar.stories.tsx
  src/views/components/calendar/Calendar.tsx
  src/views/components/calendar/CalendarBottomBar.tsx
  src/views/components/calendar/CalendarCourseCell.tsx
  src/views/components/calendar/CalendarGrid.tsx
  src/views/components/calendar/CalenderHeader.tsx
  src/views/components/calendar/utils.ts
  src/views/components/common/LogoIcon.tsx
  src/views/components/common/ScheduleTotalHoursAndCourses.tsx
  unocss.config.ts
Labels: feature

#187 feat: beta builds
  README.md
  package.json
  public/icons/icon_beta.svg
  public/icons/icon_beta_128.png
  public/icons/icon_beta_16.png
  public/icons/icon_beta_32.png
  public/icons/icon_beta_48.png
  public/icons/icon_development.svg
  public/icons/icon_development_128.png
  public/icons/icon_development_16.png
  public/icons/icon_development_32.png
  public/icons/icon_development_48.png
  public/icons/icon_production.svg
  public/icons/icon_production_128.png
  public/icons/icon_production_16.png
  public/icons/icon_production_32.png
  public/icons/icon_production_48.png
  src/manifest.ts
  unocss.config.ts
Labels: ready-for-review, feature

#192 feat: listed versioning for beta builds
  .env.development
  .env.production
  @types/css-imports.d.ts
  @types/environment.d.ts
  @types/svg-import.d.ts
  @types/vite-env.d.ts
  package.json
  src/pages/options/App.tsx
  src/views/components/calendar/CalendarFooter.tsx
  src/views/components/calendar/TeamLinks.tsx
  src/views/components/common/LogoIcon.tsx
  tsconfig.json
  vite.config.ts
Labels: ready-for-review, feature

#195 feat: added flag ;-;
  src/views/components/common/Chip.tsx
Labels: bugfix

#189 refactor: updated injected popup to match figma
  src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
Labels: ready-for-review, bugfix
