Repository Longhorn-Developers/UT-Registration-Plus, pull requests merged in 2024-11, with the labels that each got.

#327 chore: update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ready-for-review, docs

#323 feat(build): refactor gulpfile to use gulp-execa
  gulpfile.js
  package.json
  pnpm-lock.yaml
Labels: dependencies, build

#426 feat: add 404 page
  src/pages/404/Page404.tsx
  src/pages/404/index.html
  src/pages/404/index.tsx
  vite.config.ts
Labels: ready-for-review, feature

#405 feat: add CacheStore for GitHub stats and use names instead of usernames
  src/shared/storage/CacheStore.ts
  src/shared/types/CachedData.ts
  src/views/components/settings/Settings.tsx
  src/views/lib/getGitHubStats.ts
Labels: awaiting-changes, feature

#427 fix(ui): reduce left side grade distribution margin/padding
  src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
Labels: ready-for-review, bugfix

#409 feat: modify Course Block text style and time and location text
  src/shared/types/CourseMeeting.ts
  src/stories/components/calendar/CalendarCourseCell.stories.tsx
  src/views/components/calendar/CalendarCourseCell.tsx
  src/views/components/common/Text/Text.module.scss
  src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
  src/views/hooks/useFlattenedCourseSchedule.ts
Labels: UI/UX-figma

#325 feat: add explanation to grade distribution
  src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
Labels: ready-for-review, feature

#291 feat: injected button - add all courses from MyUT AND passing URL to handler
  src/manifest.ts
  src/pages/background/handler/userScheduleHandler.ts
  src/pages/background/lib/addCourse.ts
  src/pages/background/lib/addCourseByURL.ts
  src/pages/content/index.tsx
  src/shared/messages/UserScheduleMessages.ts
  src/views/components/injected/AddAllButton.tsx
  src/views/components/settings/Settings.tsx
  src/views/lib/getSiteSupport.ts
Labels: feature

#430 feat: add eslint-plugin-tsdoc
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
  src/debug/index.tsx
  src/pages/background/lib/createSchedule.ts
  src/pages/background/lib/duplicateSchedule.ts
  src/pages/background/lib/handleDuplicate.ts
  src/shared/messages/CESMessage.ts
  src/shared/messages/TabManagementMessages.ts
  src/shared/messages/UserScheduleMessages.ts
  src/shared/storage/OptionsStore.ts
  src/shared/types/CachedData.ts
  src/shared/types/Course.ts
  src/shared/types/CourseMeeting.ts
  src/shared/types/CourseSchedule.ts
  src/shared/types/Instructor.ts
  src/shared/util/colors.ts
  src/shared/util/downloadBlob.ts
  src/shared/util/icons.tsx
  src/shared/util/random.ts
  src/shared/util/string.ts
  src/shared/util/time.ts
  src/views/components/calendar/CalendarBottomBar.tsx
  src/views/components/calendar/CalendarCourseCell.tsx
  src/views/components/calendar/CalendarCourseCellColorPicker/ColorPatch.tsx
  src/views/components/calendar/CalendarCourseCellColorPicker/CourseCellColorPicker.tsx
  src/views/components/calendar/CalendarCourseCellColorPicker/HexColorEditor.tsx
  src/views/components/calendar/CalendarGrid.tsx
  src/views/components/calendar/CalendarGridCell.tsx
  src/views/components/common/ConflictsWithWarning.tsx
  src/views/components/common/CourseStatus.tsx
  src/views/components/common/List.tsx
  src/views/components/common/LogoIcon.tsx
  src/views/components/common/PopupCourseBlock.tsx
  src/views/components/common/Prompt.tsx
  src/views/components/common/ScheduleTotalHoursAndCourses.tsx
  src/views/components/common/SwitchButton.tsx
  src/views/components/common/UpdateText.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/CourseCatalogInjectedPopup.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/Description.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
  src/views/components/injected/RecruitmentBanner/RecruitmentBanner.tsx
  src/views/components/settings/Settings.tsx
  src/views/contexts/SentryContext.tsx
  src/views/hooks/useEnforceScheduleLimit.tsx
  src/views/hooks/useFlattenedCourseSchedule.ts
  src/views/hooks/useInfiniteScroll.ts
  src/views/hooks/useKeyPress.ts
  src/views/lib/CourseCatalogScraper.ts
  src/views/lib/database/queryDistribution.ts
  src/views/lib/getCourseTableRows.ts
  src/views/lib/getSiteSupport.ts
  src/views/lib/getUpdatedAtDateTimeString.ts
  src/views/lib/loadNextCourseCatalogPage.ts
Labels: dependencies, feature, docs

#289 fix: updated text when time/location not provided
  src/views/components/injected/CourseCatalogInjectedPopup/DisplayMeetingInfo.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
Labels: ready-for-review, blocked, bugfix, UI/UX-figma

#381 fix: modify shadow on-hover and animation for CC Popup filled buttons
  unocss.config.ts
Labels: ready-for-review, bugfix

#439 docs: remove redundant sentence in readme
  README.md
Labels: docs

#440 style(ui): changed tick marks to match x-axis
  src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
Labels: UI/UX-figma

#425 fix: instructor formatting errors
  src/shared/types/Instructor.ts
  src/views/components/common/PopupCourseBlock.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
  src/views/hooks/useFlattenedCourseSchedule.ts
Labels: bugfix

#388 fix: bottom-aligned all calendar elements, updated calendar header & main popup layout
  package.json
  pnpm-lock.yaml
  src/stories/components/calendar/CalendarHeader.stories.tsx
  src/views/components/calendar/Calendar.tsx
  src/views/components/calendar/CalendarHeader.tsx
  src/views/components/common/ScheduleDropdown.tsx
  src/views/components/common/ScheduleTotalHoursAndCourses.tsx
  src/views/components/settings/Settings.tsx
  unocss.config.ts
Labels: bugfix

#447 refactor: change a file name
  src/pages/background/lib/addCourse.ts
  src/pages/background/lib/importSchedule.ts
  src/stories/components/FileUpload.stories.tsx
  src/views/components/common/FileUpload.tsx
  src/views/components/settings/Settings.tsx
Labels: ready-for-review
