Repository Longhorn-Developers/UT-Registration-Plus, pull requests merged in 2025-01, with the labels that each got.

#435 fix: 4th attempt for: now able to delete schedule even if active
  src/pages/background/lib/deleteSchedule.ts
  src/views/components/common/ScheduleListItem.tsx
Labels: bugfix

#473 feat(ui): update theme colors #466
  src/shared/types/ThemeColors.ts
  src/views/components/calendar/CalendarFooter.tsx
Labels: ready-for-review, feature, UI/UX-figma

#482 feat(ui): update button variants following figma
  src/stories/components/Button.stories.tsx
  src/stories/components/FileUpload.stories.tsx
  src/stories/components/Prompt.stories.tsx
  src/views/components/PopupMain.tsx
  src/views/components/calendar/CalendarBottomBar.tsx
  src/views/components/calendar/CalendarHeader.tsx
  src/views/components/calendar/CalendarSchedules.tsx
  src/views/components/common/Button.tsx
  src/views/components/common/FileUpload.tsx
  src/views/components/common/MigrationDialog.tsx
  src/views/components/common/ScheduleListItem.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
  src/views/components/settings/Settings.tsx
  src/views/hooks/useChangelog.tsx
  unocss.config.ts
Labels: ready-for-review, feature, UI/UX-figma

#378 feat(ui): added shadows to popup buttons and course blocks
  src/views/components/PopupMain.tsx
  src/views/components/common/List.tsx
  src/views/components/common/PopupCourseBlock.tsx
Labels: UI/UX-figma

#483 feat(ui): change red text when instructor not found
  src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
Labels: ready-for-review, UI/UX-figma

#485 feat(ui): redesign grade distribution tooltip
  src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
Labels: ready-for-review, UI/UX-figma

#382 feat(ui): course color picker
  src/pages/background/handler/userScheduleHandler.ts
  src/shared/messages/UserScheduleMessages.ts
  src/shared/types/Color.ts
  src/shared/util/colors.ts
  src/shared/util/tests/colors.test.ts
  src/stories/components/calendar/CalendarBottomBar.stories.tsx
  src/stories/components/calendar/CalendarCourseCell.stories.tsx
  src/stories/components/calendar/CalendarGrid.stories.tsx
  src/stories/components/calendar/CourseCellColorPicker.stories.tsx
  src/views/components/calendar/CalendarBottomBar.tsx
  src/views/components/calendar/CalendarCourseCell.tsx
  src/views/components/calendar/CalendarCourseCellColorPicker/ColorPatch.tsx
  src/views/components/calendar/CalendarCourseCellColorPicker/CourseCellColorPicker.tsx
  src/views/components/calendar/CalendarCourseCellColorPicker/HexColorEditor.tsx
  src/views/components/calendar/CalendarGrid.tsx
  src/views/components/common/Button.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
  src/views/contexts/ColorPickerContext.tsx
  src/views/hooks/useColorPicker.ts
  src/views/hooks/useDebounce.tsx
  src/views/hooks/useFlattenedCourseSchedule.ts
  src/views/hooks/useSchedules.ts
Labels: awaiting-changes, feature, UI/UX-figma

#487 docs: add repobeats and star history
  README.md
Labels: ready-for-review, docs

#443 feat: validate login passed to background and implemented into add all injected button
  src/pages/background/handler/userScheduleHandler.ts
  src/pages/background/lib/addCourseByURL.ts
  src/shared/messages/UserScheduleMessages.ts
  src/views/components/injected/AddAllButton.tsx
Labels: ready-for-review, bugfix

#489 feat(settings): allow disabling of auto-loading courses
  src/views/components/CourseCatalogMain.tsx
Labels: ready-for-review, feature

#488 feat(settings): add option to always open calendar in new tab
  src/pages/background/handler/calendarBackgroundHandler.ts
  src/shared/storage/OptionsStore.ts
  src/views/components/settings/Settings.tsx
Labels: ready-for-review, feature

#490 feat(ui): course unique number copy button
  src/views/components/common/Button.tsx
  src/views/components/common/PopupCourseBlock.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
Labels: ready-for-review, feature, UI/UX-figma

#491 feat(ui): color picker final touches
  public/fonts/roboto-mono.woff2
  src/shared/util/colors.ts
  src/shared/util/tests/colors.test.ts
  src/views/components/calendar/CalendarCourseCellColorPicker/HexColorEditor.tsx
  src/views/hooks/useSchedules.ts
  src/views/styles/fonts.module.scss
  unocss.config.ts
Labels: ready-for-review, feature, UI/UX-figma
