Repository Longhorn-Developers/UT-Registration-Plus, pull requests merged in 2025-02, with the labels that each got.

#502 fix(ui): fix longstanding drag-and-drop duplication issue
  package.json
  pnpm-lock.yaml
  src/stories/components/Dropdown.stories.tsx
  src/stories/components/ImportantLinks.stories.tsx
  src/stories/components/List.stories.tsx
  src/views/components/PopupMain.tsx
  src/views/components/calendar/CalendarSchedules.tsx
  src/views/components/common/List.tsx
  src/views/components/common/PopupCourseBlock.tsx
  src/views/components/common/ScheduleDropdown.tsx
  src/views/components/common/ScheduleListItem.tsx
  src/views/components/common/SortableItemOverlay.tsx
  src/views/components/common/SortableList.tsx
  src/views/components/common/SortableListDragHandle.tsx
  src/views/contexts/SortableItemContext.tsx
  src/views/hooks/useCursor.tsx
Labels: ready-for-review, dependencies, feature, bugfix, UI/UX-figma

#479 feat(ui): calendar header redesign
  src/stories/components/calendar/CalendarHeader.stories.tsx
  src/views/components/calendar/Calendar.tsx
  src/views/components/calendar/CalendarBottomBar.tsx
  src/views/components/calendar/CalendarHeader.tsx
  src/views/components/calendar/CalendarHeader/CalendarHeader.module.scss
  src/views/components/calendar/CalendarHeader/CalendarHeader.tsx
  src/views/components/common/Button.tsx
  src/views/components/common/ScheduleTotalHoursAndCourses.tsx
  src/views/components/common/Text/Text.tsx
Labels: ready-for-review, feature, UI/UX-figma

#503 feat(ui): Modify Calendar Footer design and Unscheduled courses
  src/shared/types/ThemeColors.ts
  src/views/components/calendar/Calendar.tsx
  src/views/components/calendar/CalendarBottomBar.tsx
  src/views/components/common/Divider.tsx
  src/views/components/common/ScheduleListItem.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
Labels: ready-for-review, feature, UI/UX-figma

#506 feat(ui): update popup and course blocks
  src/pages/popup/index.html
  src/shared/storage/OptionsStore.ts
  src/shared/types/CourseMeeting.ts
  src/stories/components/SortableList.stories.tsx
  src/views/components/PopupMain.tsx
  src/views/components/calendar/Calendar.tsx
  src/views/components/calendar/CalendarBottomBar.tsx
  src/views/components/calendar/CalendarCourseCellColorPicker/CourseCellColorPicker.tsx
  src/views/components/calendar/CalendarHeader/CalendarHeader.tsx
  src/views/components/common/Divider.tsx
  src/views/components/common/PopupCourseBlock.tsx
  src/views/components/common/ScheduleDropdown.tsx
  src/views/components/common/ScheduleListItem.tsx
  src/views/components/settings/Settings.tsx
Labels: ready-for-review, blocked, feature, UI/UX-figma

#507 feat(build): add vite-build-logger
  src/views/components/common/ScheduleListItem.tsx
  utils/plugins/vite-build-logger.ts
  vite.config.ts
Labels: feature, build

#515 fix: import schedule file upload button
  src/shared/types/MIMEType.ts
  src/views/components/common/FileUpload.tsx
  src/views/components/settings/Settings.tsx
Labels: ready-for-review, awaiting-changes, bugfix

#534 chore(cal): update course schedule links for fall and summer 2025
  src/views/components/calendar/ResourceLinks.tsx
Labels: ready-for-review
