Repository Longhorn-Developers/UT-Registration-Plus, pull requests merged in 2025-06, with the labels that each got.

#597 docs: add pnpm and update versions
  README.md
Labels: docs

#589 feat: automatically select new or duplicated schedules
  src/pages/background/lib/createSchedule.ts
  src/pages/background/lib/duplicateSchedule.ts
Labels: bugfix

#596 feat: support summer grades, fix summer course parser
  src/shared/types/Course.ts
  src/shared/types/tests/Course.test.ts
  src/stories/components/SortableList.stories.tsx
  src/views/components/PopupMain.tsx
  src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
  src/views/lib/CourseCatalogScraper.test.ts
  src/views/lib/CourseCatalogScraper.ts
  src/views/lib/database/queryDistribution.ts
Labels: ready-for-review, bugfix, db

#593 feat: add nix flake
  .editorconfig
  .envrc
  .gitignore
  flake.lock
  flake.nix
Labels: ready-for-review, dependencies, feature, build, nix

#594 feat: export schedule button add to calendar
  src/views/components/calendar/CalendarHeader/CalendarHeader.tsx
  src/views/components/calendar/utils.ts
  src/views/components/settings/Settings.tsx
Labels: feature
