Repository Longhorn-Developers/UT-Registration-Plus, pull requests merged in 2025-03, with the labels that each got.

#536 chore: update lock file and set engine to use pnpm v10
  .github/workflows/best-practices.yml
  .github/workflows/check-types.yml
  .github/workflows/chromatic.yml
  .github/workflows/tests.yml
  Dockerfile
  package.json
  pnpm-lock.yaml
Labels: dependencies, build, ci/cd

#540 chore: use volta to pin node@20.9.0
  package.json
Labels: dependencies, docs, build

#539 feat: implement a What's New prompt
  src/pages/calendar/CalendarMain.tsx
  src/shared/storage/ExtensionStore.ts
  src/stories/components/WhatsNewPopup.stories.tsx
  src/views/components/calendar/Calendar.tsx
  src/views/components/common/WhatsNewPopup.tsx
  src/views/hooks/useWhatsNew.tsx
Labels: feature

#535 fix: ics calendar export dates
  package.json
  pnpm-lock.yaml
  src/shared/util/string.ts
  src/shared/util/tests/string.test.ts
  src/stories/injected/mocked.ts
  src/views/components/calendar/academic-calendars.ts
  src/views/components/calendar/utils.test.ts
  src/views/components/calendar/utils.ts
Labels: feature, bugfix

#569 feat: persist sidebar toggle state
  package.json
  pnpm-lock.yaml
  src/shared/storage/OptionsStore.ts
  src/views/components/calendar/Calendar.tsx
  src/views/components/common/ExtensionRoot/ExtensionRoot.tsx
Labels: ready-for-review, dependencies, feature
